### PR TITLE
Use labels instead of separate metrics

### PR DESCRIPTION
**Pull request by tony2001**
Currently there is a separate set of similar metrics for each deployment kind: 
k8s_image_availability_exporter_cronjob_*
k8s_image_availability_exporter_daemonset_*
k8s_image_availability_exporter_deployment_*
k8s_image_availability_exporter_statefulset_*

So to monitor missing images I have to use 4 different queries instead of one. Why not simplify it by using a `kind` label instead?

### CODE REVIEW

**Comment by nabokihms** [comment]
Hello, @tony2001. Thanks for opening a PR.

This will be a breaking change, but I don't hesitate to accept. 
1. The README.md file should be changed accordingly.
2. There are prometheus rules in the chart that use metric names in queries.
3. Could you please sign your commit with the following command? `git rebase HEAD~1 --signoff`

P.S. This is a surprise for me that we do not have unit tests for metrics. It would be cool if you could add one, but I understand that for this PR it is out of scope.

**Comment by tony2001** [comment]
OK, check it out again pls.

**Review by nabokihms — APPROVED** [review]
In the README.md there are still metrics in the old format, but it's ok. We will fix this later.

**Comment by nabokihms** [comment]
@tony2001 thank you for the contribution.

**Pull request merged**
